import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import assert from "node:assert/strict";
import { prepareEngineProjectExport } from "../src/main/exportEngineProject.js";
import { writeEngineSchemaExport } from "../src/main/engineProjectExport.js";
import { parseGBAProjectFile } from "../src/shared/projectFile.js";
import { resolveInterfaceTheme } from "../src/shared/interfaceThemes.js";
const app = process.cwd();
const repo = path.resolve(app, "../..");
const projectPath = path.join(app, "default-assets/templates/exemplo-gba/exemplo-gba.gba-project");
const data = parseGBAProjectFile(await readFile(projectPath, "utf8")).data;
const engine = path.join(repo, "packages/GBAStudioEngine");
const destination = process.env.GBA_THEMES_EXPORT ?? "/tmp/gba-interface-themes-validation/export";
(data.settings as any).build.enginePackPath = path.join(engine, "dist/GBAStudioEnginePack");
const prepared = prepareEngineProjectExport(data, { developmentStartScene: { name: "conselho_guardia" } });
assert(prepared.generated, prepared.error);
const scenes = data.scenas as Record<string, any>[];
assert.equal(scenes.length, 31);
for (const scene of scenes) assert(resolveInterfaceTheme(data, scene.id).theme, scene.name);
const configs = Object.values(prepared.generated.contract).filter((item: any) => item?.dialogue_ui).map((item: any) => item.dialogue_ui);
assert(configs.length >= 10);
for (const config of configs) assert.deepEqual(config.scene_skins, configs[0].scene_skins);
assert(configs[0].scene_skins.length >= 31);
assert(!configs[0].hud_scene_bindings.some((item: any) => ["conselho_guardia", "porto_lumen", "titulo"].includes(item.scene_name)));
const result = await writeEngineSchemaExport({ destination, prepared: prepared.generated, projectPath, assetcPath: path.join(engine, "tools/assetc/assetc.py"), cacheEnabled: false });
await mkdir(path.dirname(destination), { recursive: true });
const report = { scenes: scenes.length, runtimes: configs.length, sceneSkinBindings: configs[0].scene_skins.length, files: result.files.length, warnings: result.warnings ?? [], exportPath: result.destination };
await writeFile(path.join(path.dirname(destination), "report.json"), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
