#include "audio.hpp"

#include <cassert>

int main() {
    const auto& mod = audio_tracker_assets[1].patterns[0];
    const auto& mod_vibrato = audio_tracker_assets[1].patterns[1];
    const auto& mod_tremolo = audio_tracker_assets[1].patterns[2];
    const auto& s3m = audio_tracker_assets[2].patterns[0];
    const auto& s3m_vibrato = audio_tracker_assets[2].patterns[1];
    const auto& s3m_tremolo = audio_tracker_assets[2].patterns[2];
    const auto& vgm = audio_tracker_assets[3].patterns[0];

    assert(audio_sfx_asset_count == 1);
    assert(audio_music_asset_count == 1);
    assert(audio_tracker_asset_count == 4);
    assert(audio_pcm_asset_count == 4);
    assert(audio_sfx_assets[0].tones[0].frequency_hz == 880);
    assert(audio_music_assets[0].loop);
    assert(audio_tracker_assets[0].patterns[0].steps[1].channel == 3);

    assert(audio_tracker_assets[1].pattern_count == 4);
    assert(audio_tracker_assets[1].order_count == 4);
    assert(audio_tracker_assets[1].order[1] == 1);
    assert(audio_tracker_assets[1].order[2] == 2);
    assert(audio_tracker_assets[1].order[3] == 1);
    assert(mod.steps[0].duration_frames == 0);
    assert(mod.steps[0].sample_index == 0);
    assert(mod.steps[1].channel == 3);
    assert(mod.steps[1].sample_index == 0);
    assert(audio_tracker_assets[1].sample_count == 1);
    assert(mod.step_count == 54);
    assert(mod.steps[0].frequency_hz == 4095);
    assert(mod.steps[0].volume == 12);
    assert(mod.steps[1].duration_frames == 12);
    assert(mod.steps[2].volume == 6);
    assert(mod.steps[2].duration_frames == 12);
    assert(mod.steps[3].duration_frames == 24);
    assert(mod.steps[4].frequency_hz == 2133);
    assert(mod.steps[5].frequency_hz == 2537);
    assert(mod.steps[6].frequency_hz == 3196);
    assert(mod.steps[28].frequency_hz == 2133);
    assert(mod.steps[35].frequency_hz == 2260);
    assert(mod.steps[36].frequency_hz == 2133);
    assert(mod.steps[43].frequency_hz == 2013);
    assert(mod.steps[44].volume == 9);
    assert(mod.steps[44].duration_frames == 48);
    assert(mod.steps[45].frequency_hz == 2133);
    assert(mod.steps[45].duration_frames == 96);
    assert(mod.steps[46].frequency_hz == 2133);
    assert(mod.steps[46].duration_frames == 31);
    assert(mod.steps[50].frequency_hz == 2453);
    assert(mod.steps[53].frequency_hz == 2693);
    assert(mod.steps[53].duration_frames == 38);
    assert(mod_vibrato.step_count == 8);
    assert(mod_vibrato.steps[0].frequency_hz == 2133);
    assert(mod_vibrato.steps[1].frequency_hz == 2160);
    assert(mod_vibrato.steps[3].frequency_hz == 2106);
    assert(mod_vibrato.steps[7].duration_frames == 12);
    assert(mod_tremolo.step_count == 8);
    assert(mod_tremolo.steps[0].volume == 12);
    assert(mod_tremolo.steps[1].volume == 15);
    assert(mod_tremolo.steps[3].volume == 8);
    assert(mod_tremolo.steps[7].duration_frames == 12);

    assert(audio_tracker_assets[2].pattern_count == 4);
    assert(audio_tracker_assets[2].order_count == 4);
    assert(audio_tracker_assets[2].order[1] == 1);
    assert(audio_tracker_assets[2].order[2] == 2);
    assert(audio_tracker_assets[2].order[3] == 1);
    assert(s3m.steps[0].duration_frames == 0);
    assert(s3m.steps[0].sample_index == 0);
    assert(s3m.steps[1].channel == 3);
    assert(s3m.steps[1].sample_index == 0);
    assert(audio_tracker_assets[2].sample_count == 2);
    assert(s3m.step_count == 30);
    assert(s3m.steps[0].frequency_hz == 131);
    assert(s3m.steps[0].volume == 9);
    assert(s3m.steps[1].duration_frames == 12);
    assert(s3m.steps[2].volume == 6);
    assert(s3m.steps[2].duration_frames == 12);
    assert(s3m.steps[3].volume == 8);
    assert(s3m.steps[3].duration_frames == 8);
    assert(s3m.steps[4].frequency_hz == 262);
    assert(s3m.steps[4].volume == 9);
    assert(s3m.steps[4].duration_frames == 8);
    assert(s3m.steps[5].frequency_hz == 262);
    assert(s3m.steps[12].frequency_hz == 247);
    assert(s3m.steps[13].frequency_hz == 262);
    assert(s3m.steps[20].frequency_hz == 278);
    assert(s3m.steps[20].duration_frames == 2);
    assert(s3m.steps[21].frequency_hz == 262);
    assert(s3m.steps[21].duration_frames == 16);
    assert(s3m.steps[22].frequency_hz == 262);
    assert(s3m.steps[22].duration_frames == 16);
    assert(s3m.steps[25].frequency_hz == 283);
    assert(s3m.steps[29].frequency_hz == 311);
    assert(s3m.steps[29].duration_frames == 16);
    assert(s3m_vibrato.step_count == 8);
    assert(s3m_vibrato.steps[0].frequency_hz == 262);
    assert(s3m_vibrato.steps[1].frequency_hz == 265);
    assert(s3m_vibrato.steps[3].frequency_hz == 259);
    assert(s3m_vibrato.steps[7].duration_frames == 3);
    assert(s3m_tremolo.step_count == 8);
    assert(s3m_tremolo.steps[0].volume == 12);
    assert(s3m_tremolo.steps[1].volume == 15);
    assert(s3m_tremolo.steps[3].volume == 8);
    assert(s3m_tremolo.steps[7].duration_frames == 3);

    assert(audio_tracker_assets[3].order_count == 1);
    assert(vgm.step_count == 4);
    assert(vgm.steps[0].frequency_hz == 881);
    assert(vgm.steps[0].volume == 12);
    assert(vgm.steps[0].duration_frames == 2);
    assert(vgm.steps[1].frequency_hz == 1177);
    assert(vgm.steps[1].volume == 8);
    assert(vgm.steps[1].duration_frames == 1);
    assert(vgm.steps[2].frequency_hz == 1177);
    assert(vgm.steps[2].volume == 13);
    assert(vgm.steps[2].duration_frames == 2);
    assert(vgm.steps[3].channel == 4);
    assert(vgm.steps[3].frequency_hz == 512);
    assert(vgm.steps[3].volume == 10);
    assert(vgm.steps[3].duration_frames == 4);

    assert(audio_pcm_assets[0].sample_rate_hz == 8000);
    assert(!audio_pcm_assets[0].loop);
    assert(audio_pcm_assets[0].loop_start_sample == 0);
    assert(audio_pcm_assets[0].loop_end_sample == 0);
    assert(audio_pcm_assets[1].sample_rate_hz == 11025);
    assert(audio_pcm_assets[1].sample_count == 8);
    assert(audio_pcm_assets[1].loop);
    assert(audio_pcm_assets[1].loop_start_sample == 2);
    assert(audio_pcm_assets[1].loop_end_sample == 6);
    assert(audio_pcm_assets[1].samples[0] == 0);
    assert(audio_pcm_assets[1].samples[3] == 127);
    assert(audio_pcm_assets[1].samples[4] == -1);
    assert(audio_pcm_assets[1].samples[7] == -128);
    assert(audio_pcm_assets[2].sample_rate_hz == 11025);
    assert(audio_pcm_assets[2].sample_count == 8);
    assert(audio_pcm_assets[2].loop);
    assert(audio_pcm_assets[2].loop_start_sample == 2);
    assert(audio_pcm_assets[2].loop_end_sample == 6);
    assert(audio_pcm_assets[2].samples[0] == 0);
    assert(audio_pcm_assets[2].samples[3] == 127);
    assert(audio_pcm_assets[2].samples[4] == -128);
    assert(audio_pcm_assets[2].samples[7] == -32);
    assert(audio_pcm_assets[3].sample_rate_hz == 16000);
    assert(audio_pcm_assets[3].sample_count == 4);
    assert(audio_pcm_assets[3].loop);
    assert(audio_pcm_assets[3].loop_start_sample == 1);
    assert(audio_pcm_assets[3].loop_end_sample == 3);
    assert(audio_pcm_assets[3].samples[0] == -128);
    assert(audio_pcm_assets[3].samples[1] == 64);
    assert(audio_pcm_assets[3].samples[2] == -48);
    assert(audio_pcm_assets[3].samples[3] == 63);
}
