"""Generate the C view of the shared Latin font contract; no raster resampling."""
import json
from pathlib import Path


def generate(root):
    contract = json.loads((root / "engine/include/gbs/dialogue_font.json").read_text())
    glyphs = contract["glyphs"]
    lines = ["/* Generated by tools/assetc/generate_font_contract.py. */", "#pragma once", "#include <stdint.h>"]
    lines += [f"#define GBS_TEXT_GLYPH_COUNT {len(glyphs)}", "static const uint16_t gbs_font_codepoints[GBS_TEXT_GLYPH_COUNT] = {"]
    lines += ["    " + ", ".join(str(ord(g["character"])) for g in glyphs), "};"]
    lines += ["static const uint8_t gbs_font_rows[GBS_TEXT_GLYPH_COUNT][8] = {"]
    lines += ["    { " + ", ".join(str(v) for v in g["rows"]) + " }," for g in glyphs]
    lines += ["};", "static const uint16_t gbs_font_aliases[][2] = {"]
    lines += [f"    {{ {ord(a)}, {ord(b)} }}," for a, b in contract["aliases"].items()]
    lines += ["};"]
    # Preserve atlas order and alias semantics while making Latin text lookup
    # constant time. This is ROM metadata; glyph rows and source art are intact.
    glyph_indices = {g["character"]: i for i, g in enumerate(glyphs)}
    fallback = glyph_indices["?"]
    latin_indices = [glyph_indices.get(contract["aliases"].get(chr(cp), chr(cp)), fallback)
                     for cp in range(256)]
    lines += ["static const uint16_t gbs_font_latin_glyphs[256] = {"]
    lines += ["    " + ", ".join(str(i) for i in latin_indices[start:start + 16]) + ","
              for start in range(0, 256, 16)]
    lines += ["};", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[2]
    (root / "engine/include/gbs/text_font_data.h").write_text(generate(root))
